name: absent_payroll
description: "Sistem Informasi dan Penggajian Guru Honorer Pada SMP Widya Sakti Berbasis Mobile"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  json_annotation: ^4.9.0
  dart_ping_ios: ^4.0.2
  property_change_notifier: ^0.3.0
  intl: ^0.19.0
  timeago: ^3.6.1
  flutter_native_splash: ^2.4.0
  google_maps_flutter: ^2.2.8
  geolocator: ^11.0.0
  location: ^6.0.1
  maps_toolkit: ^3.0.0
  image_picker: ^1.1.0
  image_cropper: ^5.0.1
  flutter_svg: ^2.0.10+1
  flutter_easyrefresh: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: resources/splash.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/logo_think_foward_black.png"
  image_path_android: "resources/logo_think_foward_black.png"

flutter:
  uses-material-design: true